[build]
  # Build inside the `twiller` subfolder (Netlify will change directory to this base)
  base = "twiller"
  # Run install including devDependencies (react-scripts lives in devDependencies) then build
  command = "npm ci --include=dev && npm run build"
  # Publish the build output directory relative to the base
  publish = "build"

[context.production.environment]
  # Example: set your API base URL here in Netlify dashboard instead of committing secrets
  # REACT_APP_API_URL = "https://your-backend.example.com"
