[build]
  # Build command: first install dependencies inside the `twiller` folder, then build
  command = "npm --prefix twiller install && npm --prefix twiller run build"
  # Publish the build output directory
  publish = "twiller/build"

[context.production.environment]
  # Example: set your API base URL here in Netlify dashboard instead of committing secrets
  # REACT_APP_API_URL = "https://your-backend.example.com"
